#!/usr/bin/env python3
"""Bounded symbol index. No imports of application code or third-party tools."""
import argparse
import ast
import os
from pathlib import Path
import re
import tempfile

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs/REPO_MAP.md"
# Only these owned source/documentation trees are traversed. Prune before descent.
TREES = ("src", "apps", "packages", "tests", "scripts", ".scripts", "tools", "docs", ".github", ".githooks")
EXCLUDED_DIRS = set("""
.git node_modules vendor .venv venv env ENV dist build target lib
__pycache__ .pytest_cache .ruff_cache .uv_cache .cache .npm-cache .tox
.hypothesis .stryker-tmp coverage htmlcov reports playwright-report test-results
.shots .browsers instance .idea .vscode .claude fixtures __fixtures__
snapshots __snapshots__ assets
""".split())
EXCLUDED_PATHS = {"src/crossword/static/react", "src/crossword/static/lib"}
EXTENSIONS = {".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".sh", ".md", ".html", ".css", ".toml", ".json", ".yaml", ".yml"}
ROOT_FILES = {"AGENTS.md", "README.md", "SETUP.md", "TESTING.md", "CELL_MODEL.md", "SPECIAL_CHARACTERS.md", "Makefile", "Dockerfile", "run.py", "start.sh", "conftest.py", "package.json", "pyproject.toml", ".cursorrules", ".python-version", ".node-version", ".pre-commit-config.yaml"}
MAX_BYTES = 256_000
MAX_SYMBOLS = 16
JS_DECL = re.compile(r"^\s*(?:export\s+)?(?:default\s+)?(?:declare\s+)?(?:async\s+)?(?:function\s*\*?\s*|class\s+|interface\s+|type\s+|enum\s+)([A-Za-z_$][\w$]*)")
JS_EXPORT = re.compile(r"^\s*export\s+(?:const|let|var)\s+([A-Za-z_$][\w$]*)")
JS_METHOD = re.compile(r"^\s*(?:async\s+)?([A-Za-z_$][\w$]*)\s*\([^;{}]*\)\s*\{")
JS_ARROW = re.compile(r"^\s*(?:const|let)\s+([A-Za-z_$][\w$]*)\s*=.*=>")


def allowed(path):
    rel = path.relative_to(ROOT)
    name = path.name
    return (
        not path.is_symlink()
        and not any(part in EXCLUDED_DIRS for part in rel.parts[:-1])
        and not any(rel.as_posix() == prefix or rel.as_posix().startswith(prefix + "/") for prefix in EXCLUDED_PATHS)
        and not name.startswith(".env")
        and "lock" not in name.lower()
        and not any(part in name for part in (".min.", ".bundle.", ".generated.", ".snap"))
        and path != OUTPUT
        and (name in ROOT_FILES or path.suffix in EXTENSIONS)
    )


def candidates():
    paths = {path for path in ROOT.iterdir() if path.is_file() and allowed(path)}
    for tree in TREES:
        base = ROOT / tree
        if base.is_symlink() or not base.is_dir():
            continue
        for directory, dirs, files in os.walk(base, followlinks=False):
            parent = Path(directory)
            dirs[:] = sorted(d for d in dirs if d not in EXCLUDED_DIRS
                             and not (parent / d).is_symlink()
                             and (parent / d).relative_to(ROOT).as_posix() not in EXCLUDED_PATHS)
            paths.update(parent / name for name in files if allowed(parent / name))
    def sort_key(path):
        rel = path.relative_to(ROOT)
        return ("" if len(rel.parts) == 1 else rel.parts[0], rel.as_posix())
    return sorted(paths, key=sort_key)


def symbols(path, text):
    result = []
    if path.suffix == ".py":
        try:
            tree = ast.parse(text)
        except SyntaxError:
            return [], "Python parse error; inspect source"
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                result.append((node.name, node.lineno))
                if isinstance(node, ast.ClassDef):
                    result.extend((f"{node.name}.{child.name}", child.lineno)
                                  for child in node.body
                                  if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)))
    elif path.suffix in {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}:
        for number, line in enumerate(text.splitlines(), 1):
            match = JS_DECL.match(line) or JS_EXPORT.match(line) or JS_ARROW.match(line) or JS_METHOD.match(line)
            if match and match[1] not in {"if", "for", "while", "switch", "catch", "with"}:
                result.append((match[1], number))
    # Names/line numbers only; never emit bodies, test data, or arbitrary text.
    return list(dict.fromkeys(result)), ""


def render():
    lines = [
        "# Repository Map", "",
        "Generated by `.scripts/generate-repo-map.sh`; do not edit manually.", "",
        "## Navigation", "",
        "- `src/crossword/`: Flask routes, parsing/models, SQLAlchemy, Vue sources and templates.",
        "- `apps/react/`: React port, controller, desktop/mobile behavior and parity tests.",
        "- `packages/domain/`, `packages/application/`, `packages/persistence/`: typed core and storage.",
        "- `tests/`: Python, legacy JavaScript, and browser tests; fixtures are omitted.",
        "- `scripts/`, `.scripts/`, `tools/`: build/quality/index helpers and offline tooling.",
        "- `docs/plans/README.md`: architecture/product roadmap; `docs/adr/`: decisions.", "",
        "## Index contract", "",
        "Offline lightweight symbol dump: Python AST (top-level definitions and class methods);",
        "JS/TS line-based declaration/method heuristic (may omit multiline declarations or match comments).",
        "Other files and tests are path-only. At most 16 symbols/file; `+N more` means search that file.",
        "Paths sorted deterministically; no timestamps or source bodies. Read source to confirm line hints.",
        "Only owned trees are scanned; dependency/VCS/private/cache/report/build directories and symlinks",
        "are pruned before descent. Lockfiles, minified/bundled/generated code, fixtures/snapshots and binary",
        "assets are excluded. Files over 256 KB or with lines over 1,000 characters are path-only.",
        "Run `bash .scripts/generate-repo-map.sh --check` to detect drift without writing.", "",
    ]
    current = None
    for path in candidates():
        rel = path.relative_to(ROOT).as_posix()
        group = rel.split("/")[0] if "/" in rel else "Root configuration & entry files"
        if group != current:
            lines.extend(["", f"## {group}", ""])
            current = group
        note = ""
        found = []
        is_test = path.name.startswith("test_") or any(part in path.name for part in (".test.", ".spec.")) or rel.startswith("tests/")
        if path.stat().st_size > MAX_BYTES:
            note = "large file; path only"
        elif not is_test and path.suffix in {".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}:
            text = path.read_text(encoding="utf-8")
            if any(len(line) > 1000 for line in text.splitlines()):
                note = "long-line source; path only"
            else:
                found, note = symbols(path, text)
        detail = ", ".join(f"`{name}:{line}`" for name, line in found[:MAX_SYMBOLS])
        if len(found) > MAX_SYMBOLS:
            detail += f" (+{len(found) - MAX_SYMBOLS} more)"
        if note:
            detail = note
        lines.append(f"- `{rel}`" + (f" — {detail}" if detail else ""))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the map is missing or stale")
    args = parser.parse_args()
    if OUTPUT.parent.is_symlink() or OUTPUT.is_symlink():
        parser.error("refusing symlinked output directory/file")
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            parser.exit(1, "Repository map is missing or stale; run bash .scripts/generate-repo-map.sh\n")
        print("Repository map is current.")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    # Atomic replacement keeps a failed run from truncating the last valid map.
    name = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=OUTPUT.parent, delete=False) as temporary:
            name = temporary.name
            temporary.write(content)
        os.chmod(name, 0o644)
        os.replace(name, OUTPUT)
    finally:
        if name and os.path.exists(name):
            os.unlink(name)
    print(f"Wrote docs/REPO_MAP.md ({len(content.encode('utf-8')):,} bytes).")


if __name__ == "__main__":
    main()
